CREATE TABLE USER (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR2(255),
    LOGIN VARCHAR2(255),
    PASSWORD VARCHAR2(255),
    SALT VARCHAR2(255)
);

CREATE TABLE ROLE (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR2(255),
    RESOURCE VARCHAR2(255),
    USER_ID INT
);

CREATE TABLE ACCOUNTING (
    VOLUME INT,
    DATE_START DATE,
    DATE_END DATE,
    ROLE_ID INT
);

ALTER TABLE ROLE
    ADD FOREIGN KEY (USER_ID)
    REFERENCES USER(ID);

ALTER TABLE ACCOUNTING
    ADD FOREIGN KEY (ROLE_ID)
    REFERENCES ROLE(ID);

INSERT INTO USER(NAME, LOGIN, PASSWORD, SALT)
    VALUES('John Doe', 'jdoe', 'ce6ee9f2534a5b5a2ab90744fb2c384a', 'e17bmb985h1atd7hpm9qs494tg');
INSERT INTO USER(NAME, LOGIN, PASSWORD, SALT)
    VALUES('Jane Row', 'jrow', 'afb1413294a2e947b5d9679994c0ddb7', 'bcjv148r3flakcmrsgf521smas');

INSERT INTO ROLE(NAME, RESOURCE, USER_ID)
    VALUES('READ', 'a', 1);
INSERT INTO ROLE(NAME, RESOURCE, USER_ID)
    VALUES('WRITE', 'a.b', 1);
INSERT INTO ROLE(NAME, RESOURCE, USER_ID)
    VALUES('EXECUTE', 'a.b.c', 2);
INSERT INTO ROLE(NAME, RESOURCE, USER_ID)
    VALUES('EXECUTE', 'a.bc', 1);